from fastapi import APIRouter

from . import (
    about,
    activity,
    arrmeta,
    arrqueue,
    auth,
    books,
    cleanup,
    credits,
    dashboard,
    diagnose,
    discover,
    hooks,
    ical_settings,
    importing,
    indexers,
    library,
    movies,
    opds_settings,
    people,
    plex,
    popular,
    posters,
    profiles,
    reading,
    releases,
    requests,
    series,
    settings,
    subtitles,
    system,
    tasks,
    tools,
    torrentactions,
    torrents,
    wanted,
    watchstats,
)

router = APIRouter(prefix="/api/v1")
router.include_router(about.router)
router.include_router(activity.router)
router.include_router(dashboard.router)
router.include_router(books.router)
router.include_router(diagnose.router)
router.include_router(system.router)
router.include_router(tasks.router)
router.include_router(plex.router)
router.include_router(popular.router)
router.include_router(subtitles.router)
router.include_router(torrents.router)
router.include_router(torrentactions.router)
router.include_router(importing.router)
router.include_router(arrqueue.router)
router.include_router(posters.router)
router.include_router(profiles.router)
router.include_router(discover.router)
router.include_router(releases.router)
router.include_router(requests.router)
router.include_router(indexers.router)
router.include_router(library.router)
router.include_router(movies.router)
router.include_router(series.router)
router.include_router(credits.router)
router.include_router(people.router)
router.include_router(cleanup.router)
router.include_router(reading.router)
router.include_router(opds_settings.router)
router.include_router(ical_settings.router)
router.include_router(tools.router)
router.include_router(watchstats.router)
router.include_router(wanted.router)
router.include_router(arrmeta.router)
router.include_router(settings.router)
router.include_router(auth.router)
router.include_router(hooks.router)
