/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Queue */
        get: operations["queue_api_v1_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Torrents */
        get: operations["torrents_api_v1_torrents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar */
        get: operations["calendar_api_v1_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_v1_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History All
         * @description Merged, consolidated history across both apps, paged 50/app.
         */
        get: operations["history_all_api_v1_history_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexers/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indexer Stats */
        get: operations["indexer_stats_api_v1_indexers_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/qbittorrent/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Qbit Pause */
        post: operations["qbit_pause_api_v1_torrents_qbittorrent_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/qbittorrent/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Qbit Resume */
        post: operations["qbit_resume_api_v1_torrents_qbittorrent_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/qbittorrent/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Qbit Delete */
        post: operations["qbit_delete_api_v1_torrents_qbittorrent_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/transmission/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tm Pause */
        post: operations["tm_pause_api_v1_torrents_transmission_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/transmission/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tm Resume */
        post: operations["tm_resume_api_v1_torrents_transmission_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/transmission/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tm Delete */
        post: operations["tm_delete_api_v1_torrents_transmission_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{client}/{torrent_id}/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Torrent Details */
        get: operations["torrent_details_api_v1_torrents__client___torrent_id__details_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{client}/recheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Torrent Recheck */
        post: operations["torrent_recheck_api_v1_torrents__client__recheck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{client}/{torrent_id}/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Torrent Limits */
        post: operations["torrent_limits_api_v1_torrents__client___torrent_id__limits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/qbittorrent/{torrent_id}/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Torrent Category */
        post: operations["torrent_category_api_v1_torrents_qbittorrent__torrent_id__category_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/{app}/{item_id}/blocklist-retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Blocklist Retry */
        post: operations["blocklist_retry_api_v1_queue__app___item_id__blocklist_retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/{app}/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Queue Item */
        delete: operations["remove_queue_item_api_v1_queue__app___item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/discover/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discover Movies */
        get: operations["discover_movies_api_v1_discover_movies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/discover/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discover Series */
        get: operations["discover_series_api_v1_discover_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Movies */
        get: operations["search_movies_api_v1_search_movies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Series */
        get: operations["search_series_api_v1_search_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Releases */
        get: operations["search_releases_api_v1_search_releases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/grab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grab Release */
        post: operations["grab_release_api_v1_releases_grab_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/movie/{movie_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Movie Releases */
        get: operations["movie_releases_api_v1_releases_movie__movie_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/series/{series_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Series Releases */
        get: operations["series_releases_api_v1_releases_series__series_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{app}/grab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grab Arr Release */
        post: operations["grab_arr_release_api_v1_releases__app__grab_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/options/{app}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Options */
        get: operations["options_api_v1_options__app__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Movie */
        post: operations["add_movie_api_v1_movies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Series */
        post: operations["add_series_api_v1_series_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexers/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indexer Schemas */
        get: operations["indexer_schemas_api_v1_indexers_schemas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexers/test-new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test New Indexer */
        post: operations["test_new_indexer_api_v1_indexers_test_new_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indexers */
        get: operations["indexers_api_v1_indexers_get"];
        put?: never;
        /** Add Indexer */
        post: operations["add_indexer_api_v1_indexers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexers/{indexer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle Indexer */
        patch: operations["toggle_indexer_api_v1_indexers__indexer_id__patch"];
        trace?: never;
    };
    "/api/v1/indexers/{indexer_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Indexer */
        post: operations["test_indexer_api_v1_indexers__indexer_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Library Movies */
        get: operations["library_movies_api_v1_library_movies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Library Series */
        get: operations["library_series_api_v1_library_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/movies/{movie_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Movie */
        delete: operations["delete_movie_api_v1_library_movies__movie_id__delete"];
        options?: never;
        head?: never;
        /** Update Movie */
        patch: operations["update_movie_api_v1_library_movies__movie_id__patch"];
        trace?: never;
    };
    "/api/v1/library/series/{series_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Series Detail */
        get: operations["series_detail_api_v1_library_series__series_id__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/series/{series_id}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Series Episodes */
        get: operations["series_episodes_api_v1_library_series__series_id__episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/series/{series_id}/seasons/{season}/monitor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Season Monitor */
        post: operations["season_monitor_api_v1_library_series__series_id__seasons__season__monitor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/series/{series_id}/seasons/{season}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Season Search */
        post: operations["season_search_api_v1_library_series__series_id__seasons__season__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/episodes/monitor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Episodes Monitor */
        patch: operations["episodes_monitor_api_v1_library_episodes_monitor_patch"];
        trace?: never;
    };
    "/api/v1/library/episodes/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Episodes Search */
        post: operations["episodes_search_api_v1_library_episodes_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/series/{series_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Series */
        delete: operations["delete_series_api_v1_library_series__series_id__delete"];
        options?: never;
        head?: never;
        /** Update Series */
        patch: operations["update_series_api_v1_library_series__series_id__patch"];
        trace?: never;
    };
    "/api/v1/library/{app}/{item_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Search */
        post: operations["trigger_search_api_v1_library__app___item_id__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quality Profiles */
        get: operations["quality_profiles_api_v1_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Services */
        get: operations["services_api_v1_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All Settings */
        get: operations["all_settings_api_v1_settings_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/services/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Settings */
        put: operations["save_settings_api_v1_settings_services__name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats History */
        get: operations["stats_history_api_v1_stats_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/services/{name}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Service */
        post: operations["test_service_api_v1_settings_services__name__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddIndexerIn */
        AddIndexerIn: {
            /** Schema Name */
            schema_name: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Field Values
             * @default {}
             */
            field_values: {
                [key: string]: unknown;
            };
        };
        /** AddMovieIn */
        AddMovieIn: {
            /** Tmdb Id */
            tmdb_id: number;
            /** Title */
            title: string;
            /** Quality Profile Id */
            quality_profile_id: number;
            /** Root Folder Path */
            root_folder_path: string;
            /**
             * Monitored
             * @default true
             */
            monitored: boolean;
            /**
             * Search Now
             * @default true
             */
            search_now: boolean;
        };
        /** AddSeriesIn */
        AddSeriesIn: {
            /** Tvdb Id */
            tvdb_id: number;
            /** Title */
            title: string;
            /** Quality Profile Id */
            quality_profile_id: number;
            /** Root Folder Path */
            root_folder_path: string;
            /**
             * Monitored
             * @default true
             */
            monitored: boolean;
            /**
             * Season Folder
             * @default true
             */
            season_folder: boolean;
            /**
             * Search Now
             * @default true
             */
            search_now: boolean;
        };
        /** ArrReleaseOut */
        ArrReleaseOut: {
            /** Guid */
            guid: string;
            /** Indexer Id */
            indexer_id: number;
            /** Indexer */
            indexer?: string | null;
            /** Title */
            title: string;
            /** Quality */
            quality?: string | null;
            /** Size */
            size?: number | null;
            /** Seeders */
            seeders?: number | null;
            /** Leechers */
            leechers?: number | null;
            /** Age Days */
            age_days?: number | null;
            /**
             * Approved
             * @default true
             */
            approved: boolean;
            /**
             * Rejections
             * @default []
             */
            rejections: string[];
        };
        /** CalendarItemOut */
        CalendarItemOut: {
            /**
             * App
             * @enum {string}
             */
            app: "radarr" | "sonarr";
            /** Title */
            title: string;
            /** Date */
            date?: string | null;
            /**
             * Has File
             * @default false
             */
            has_file: boolean;
            /** Extra */
            extra?: string | null;
        };
        /** CalendarResponse */
        CalendarResponse: {
            radarr: components["schemas"]["ServiceBlock_list_CalendarItemOut__"];
            sonarr: components["schemas"]["ServiceBlock_list_CalendarItemOut__"];
        };
        /** EpisodeIdsIn */
        EpisodeIdsIn: {
            /** Ids */
            ids: number[];
        };
        /** EpisodeMonitorIn */
        EpisodeMonitorIn: {
            /** Ids */
            ids: number[];
            /** Monitored */
            monitored: boolean;
        };
        /** EpisodeOut */
        EpisodeOut: {
            /** Id */
            id: number;
            /** Season */
            season: number;
            /** Episode */
            episode: number;
            /** Title */
            title?: string | null;
            /** Air Date */
            air_date?: string | null;
            /**
             * Has File
             * @default false
             */
            has_file: boolean;
            /**
             * Monitored
             * @default false
             */
            monitored: boolean;
        };
        /** GrabIn */
        GrabIn: {
            /** Guid */
            guid: string;
            /** Indexer Id */
            indexer_id: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthItemOut */
        HealthItemOut: {
            /** Type */
            type?: string | null;
            /** Message */
            message?: string | null;
        };
        /** HistoryEventOut */
        HistoryEventOut: {
            /** Type */
            type: string;
            /** Date */
            date: string;
        };
        /**
         * HistoryItemOut
         * @description One release/torrent with every history event that happened to it.
         */
        HistoryItemOut: {
            /**
             * App
             * @enum {string}
             */
            app: "radarr" | "sonarr";
            /** Title */
            title: string;
            /** Date */
            date: string;
            /** Quality */
            quality?: string | null;
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["HistoryEventOut"][];
        };
        /** HistoryPageOut */
        HistoryPageOut: {
            /** Items */
            items: components["schemas"]["HistoryItemOut"][];
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
        };
        /** HistoryResponse */
        HistoryResponse: {
            radarr: components["schemas"]["ServiceBlock_list_HistoryItemOut__"];
            sonarr: components["schemas"]["ServiceBlock_list_HistoryItemOut__"];
        };
        /** IndexerOut */
        IndexerOut: {
            /** Id */
            id: number;
            /** Name */
            name?: string | null;
            /**
             * Enable
             * @default false
             */
            enable: boolean;
            /** Protocol */
            protocol?: string | null;
            /** Privacy */
            privacy?: string | null;
        };
        /** IndexerStatOut */
        IndexerStatOut: {
            /** Name */
            name?: string | null;
            /**
             * Queries
             * @default 0
             */
            queries: number;
            /**
             * Grabs
             * @default 0
             */
            grabs: number;
            /**
             * Avg Response Ms
             * @default 0
             */
            avg_response_ms: number;
        };
        /** IndexerStatsOut */
        IndexerStatsOut: {
            /** Enabled */
            enabled: number;
            /** Total */
            total: number;
            /** Health */
            health: components["schemas"]["HealthItemOut"][];
            /** Stats */
            stats: components["schemas"]["IndexerStatOut"][];
        };
        /** LibraryMovieOut */
        LibraryMovieOut: {
            /** Id */
            id: number;
            /** Title */
            title?: string | null;
            /** Year */
            year?: number | null;
            /**
             * Monitored
             * @default false
             */
            monitored: boolean;
            /**
             * Has File
             * @default false
             */
            has_file: boolean;
            /**
             * Size On Disk
             * @default 0
             */
            size_on_disk: number;
            /** Quality Profile Id */
            quality_profile_id?: number | null;
        };
        /** LibrarySeriesOut */
        LibrarySeriesOut: {
            /** Id */
            id: number;
            /** Title */
            title?: string | null;
            /** Year */
            year?: number | null;
            /**
             * Monitored
             * @default false
             */
            monitored: boolean;
            /** Status */
            status?: string | null;
            /**
             * Episode Count
             * @default 0
             */
            episode_count: number;
            /**
             * Episode File Count
             * @default 0
             */
            episode_file_count: number;
            /**
             * Size On Disk
             * @default 0
             */
            size_on_disk: number;
            /** Quality Profile Id */
            quality_profile_id?: number | null;
        };
        /** LibraryUpdateIn */
        LibraryUpdateIn: {
            /** Monitored */
            monitored?: boolean | null;
            /** Quality Profile Id */
            quality_profile_id?: number | null;
        };
        /** MonitorIn */
        MonitorIn: {
            /** Monitored */
            monitored: boolean;
        };
        /** OptionsOut */
        OptionsOut: {
            /** Quality Profiles */
            quality_profiles: components["schemas"]["QualityProfileOut"][];
            /** Root Folders */
            root_folders: components["schemas"]["RootFolderOut"][];
        };
        /** QualityProfileOut */
        QualityProfileOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** QueueItemOut */
        QueueItemOut: {
            /**
             * App
             * @enum {string}
             */
            app: "radarr" | "sonarr";
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Tracked State */
            tracked_state?: string | null;
            /** Size */
            size: number;
            /** Size Left */
            size_left: number;
            /** Time Left */
            time_left?: string | null;
            /**
             * Errors
             * @default []
             */
            errors: string[];
            /** Movie Id */
            movie_id?: number | null;
            /** Series Id */
            series_id?: number | null;
            /** Episode Id */
            episode_id?: number | null;
        };
        /** QueueResponse */
        QueueResponse: {
            radarr: components["schemas"]["ServiceBlock_list_QueueItemOut__"];
            sonarr: components["schemas"]["ServiceBlock_list_QueueItemOut__"];
        };
        /** ReleaseOut */
        ReleaseOut: {
            /** Guid */
            guid: string;
            /** Indexer Id */
            indexer_id: number;
            /** Indexer */
            indexer?: string | null;
            /** Title */
            title: string;
            /** Size */
            size?: number | null;
            /** Seeders */
            seeders?: number | null;
            /** Leechers */
            leechers?: number | null;
            /** Age Days */
            age_days?: number | null;
            /** Download Url */
            download_url?: string | null;
        };
        /** RootFolderOut */
        RootFolderOut: {
            /** Id */
            id: number;
            /** Path */
            path: string;
            /** Free Space */
            free_space?: number | null;
        };
        /** SearchResultOut */
        SearchResultOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "movie" | "series";
            /** Title */
            title: string;
            /** Year */
            year?: number | null;
            /** Overview */
            overview?: string | null;
            /** Remote Id */
            remote_id: number;
            /** Poster */
            poster?: string | null;
            /**
             * In Library
             * @default false
             */
            in_library: boolean;
            /** Imdb Id */
            imdb_id?: string | null;
            /** Tmdb Id */
            tmdb_id?: number | null;
            /** Library Id */
            library_id?: number | null;
            /** Monitored */
            monitored?: boolean | null;
            /** Quality Profile Id */
            quality_profile_id?: number | null;
            /** Has File */
            has_file?: boolean | null;
        };
        /** SeasonOut */
        SeasonOut: {
            /** Number */
            number: number;
            /** Monitored */
            monitored: boolean;
            /**
             * Episode Count
             * @default 0
             */
            episode_count: number;
            /**
             * Episode File Count
             * @default 0
             */
            episode_file_count: number;
            /**
             * Size On Disk
             * @default 0
             */
            size_on_disk: number;
        };
        /** SeriesDetailOut */
        SeriesDetailOut: {
            /** Id */
            id: number;
            /** Title */
            title?: string | null;
            /** Seasons */
            seasons: components["schemas"]["SeasonOut"][];
        };
        /** ServiceBlock[IndexerStatsOut] */
        ServiceBlock_IndexerStatsOut_: {
            /** Ok */
            ok: boolean;
            data?: components["schemas"]["IndexerStatsOut"] | null;
            /** Error */
            error?: string | null;
            /** Stale Age Seconds */
            stale_age_seconds?: number | null;
        };
        /** ServiceBlock[TorrentGroupOut] */
        ServiceBlock_TorrentGroupOut_: {
            /** Ok */
            ok: boolean;
            data?: components["schemas"]["TorrentGroupOut"] | null;
            /** Error */
            error?: string | null;
            /** Stale Age Seconds */
            stale_age_seconds?: number | null;
        };
        /** ServiceBlock[list[CalendarItemOut]] */
        ServiceBlock_list_CalendarItemOut__: {
            /** Ok */
            ok: boolean;
            /** Data */
            data?: components["schemas"]["CalendarItemOut"][] | null;
            /** Error */
            error?: string | null;
            /** Stale Age Seconds */
            stale_age_seconds?: number | null;
        };
        /** ServiceBlock[list[HistoryItemOut]] */
        ServiceBlock_list_HistoryItemOut__: {
            /** Ok */
            ok: boolean;
            /** Data */
            data?: components["schemas"]["HistoryItemOut"][] | null;
            /** Error */
            error?: string | null;
            /** Stale Age Seconds */
            stale_age_seconds?: number | null;
        };
        /** ServiceBlock[list[QueueItemOut]] */
        ServiceBlock_list_QueueItemOut__: {
            /** Ok */
            ok: boolean;
            /** Data */
            data?: components["schemas"]["QueueItemOut"][] | null;
            /** Error */
            error?: string | null;
            /** Stale Age Seconds */
            stale_age_seconds?: number | null;
        };
        /** ServiceInfoOut */
        ServiceInfoOut: {
            /** Service */
            service: string;
            /** Configured */
            configured: boolean;
        };
        /** ServiceSettingsIn */
        ServiceSettingsIn: {
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Api Key
             * @default
             */
            api_key: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Password
             * @default
             */
            password: string;
        };
        /** ServiceSettingsOut */
        ServiceSettingsOut: {
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Api Key
             * @default
             */
            api_key: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Password
             * @default
             */
            password: string;
            /**
             * Configured
             * @default false
             */
            configured: boolean;
        };
        /** ServiceStatus */
        ServiceStatus: {
            /**
             * Service
             * @enum {string}
             */
            service: "radarr" | "sonarr" | "prowlarr" | "qbittorrent" | "transmission" | "overseerr";
            /** Ok */
            ok: boolean;
            /** Version */
            version?: string | null;
            /** Error */
            error?: string | null;
        };
        /** StatsSampleOut */
        StatsSampleOut: {
            /** Ts */
            ts: number;
            /**
             * Movies
             * @default 0
             */
            movies: number;
            /**
             * Series
             * @default 0
             */
            series: number;
            /**
             * Episode Files
             * @default 0
             */
            episode_files: number;
            /**
             * Library Bytes
             * @default 0
             */
            library_bytes: number;
            /**
             * Torrents Qbit
             * @default 0
             */
            torrents_qbit: number;
            /**
             * Torrents Tm
             * @default 0
             */
            torrents_tm: number;
            /**
             * Indexer Grabs
             * @default 0
             */
            indexer_grabs: number;
            /**
             * Indexer Queries
             * @default 0
             */
            indexer_queries: number;
        };
        /** TorrentActionIn */
        TorrentActionIn: {
            /** Ids */
            ids: string[];
        };
        /** TorrentCategoryIn */
        TorrentCategoryIn: {
            /** Category */
            category: string;
        };
        /** TorrentDeleteIn */
        TorrentDeleteIn: {
            /** Ids */
            ids: string[];
            /**
             * Delete Data
             * @default false
             */
            delete_data: boolean;
        };
        /** TorrentDetailsOut */
        TorrentDetailsOut: {
            /** Files */
            files: components["schemas"]["TorrentFileOut"][];
            /**
             * Dl Limit Kib
             * @default 0
             */
            dl_limit_kib: number;
            /**
             * Ul Limit Kib
             * @default 0
             */
            ul_limit_kib: number;
            /** Category */
            category?: string | null;
            /**
             * Categories
             * @default []
             */
            categories: string[];
        };
        /** TorrentFileOut */
        TorrentFileOut: {
            /** Name */
            name: string;
            /** Size */
            size: number;
            /** Progress */
            progress: number;
        };
        /** TorrentGroupOut */
        TorrentGroupOut: {
            /** Torrents */
            torrents: components["schemas"]["TorrentOut"][];
            totals: components["schemas"]["TransferTotals"];
        };
        /** TorrentLimitsIn */
        TorrentLimitsIn: {
            /**
             * Dl Kib
             * @default 0
             */
            dl_kib: number;
            /**
             * Ul Kib
             * @default 0
             */
            ul_kib: number;
        };
        /** TorrentOut */
        TorrentOut: {
            /**
             * Client
             * @enum {string}
             */
            client: "qbittorrent" | "transmission";
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** State */
            state: string;
            /** Progress */
            progress: number;
            /** Size */
            size: number;
            /** Dl Speed */
            dl_speed: number;
            /** Ul Speed */
            ul_speed: number;
            /** Eta */
            eta?: number | null;
            /** Ratio */
            ratio?: number | null;
            /** Added On */
            added_on?: number | null;
            /** Tracker */
            tracker?: string | null;
            /** Error */
            error?: string | null;
        };
        /** TorrentsResponse */
        TorrentsResponse: {
            qbittorrent: components["schemas"]["ServiceBlock_TorrentGroupOut_"];
            transmission: components["schemas"]["ServiceBlock_TorrentGroupOut_"];
        };
        /** TransferTotals */
        TransferTotals: {
            /** Dl Speed */
            dl_speed: number;
            /** Ul Speed */
            ul_speed: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    status_api_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"][];
                };
            };
        };
    };
    queue_api_v1_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
        };
    };
    torrents_api_v1_torrents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TorrentsResponse"];
                };
            };
        };
    };
    calendar_api_v1_calendar_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_v1_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
        };
    };
    history_all_api_v1_history_all_get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    indexer_stats_api_v1_indexers_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceBlock_IndexerStatsOut_"];
                };
            };
        };
    };
    qbit_pause_api_v1_torrents_qbittorrent_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TorrentActionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    qbit_resume_api_v1_torrents_qbittorrent_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TorrentActionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    qbit_delete_api_v1_torrents_qbittorrent_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TorrentDeleteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tm_pause_api_v1_torrents_transmission_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TorrentActionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tm_resume_api_v1_torrents_transmission_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TorrentActionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tm_delete_api_v1_torrents_transmission_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TorrentDeleteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    torrent_details_api_v1_torrents__client___torrent_id__details_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client: string;
                torrent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TorrentDetailsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    torrent_recheck_api_v1_torrents__client__recheck_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TorrentActionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    torrent_limits_api_v1_torrents__client___torrent_id__limits_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client: string;
                torrent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TorrentLimitsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    torrent_category_api_v1_torrents_qbittorrent__torrent_id__category_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                torrent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TorrentCategoryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    blocklist_retry_api_v1_queue__app___item_id__blocklist_retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_queue_item_api_v1_queue__app___item_id__delete: {
        parameters: {
            query?: {
                remove_from_client?: boolean;
                blocklist?: boolean;
            };
            header?: never;
            path: {
                app: string;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_movies_api_v1_discover_movies_get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_series_api_v1_discover_series_get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_movies_api_v1_search_movies_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_series_api_v1_search_series_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_releases_api_v1_search_releases_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grab_release_api_v1_releases_grab_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrabIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    movie_releases_api_v1_releases_movie__movie_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArrReleaseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    series_releases_api_v1_releases_series__series_id__get: {
        parameters: {
            query?: {
                season?: number | null;
                episode_id?: number | null;
            };
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArrReleaseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grab_arr_release_api_v1_releases__app__grab_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrabIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    options_api_v1_options__app__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_movie_api_v1_movies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMovieIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_series_api_v1_series_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSeriesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    indexer_schemas_api_v1_indexers_schemas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    test_new_indexer_api_v1_indexers_test_new_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddIndexerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    indexers_api_v1_indexers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexerOut"][];
                };
            };
        };
    };
    add_indexer_api_v1_indexers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddIndexerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_indexer_api_v1_indexers__indexer_id__patch: {
        parameters: {
            query: {
                enable: boolean;
            };
            header?: never;
            path: {
                indexer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_indexer_api_v1_indexers__indexer_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                indexer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    library_movies_api_v1_library_movies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryMovieOut"][];
                };
            };
        };
    };
    library_series_api_v1_library_series_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibrarySeriesOut"][];
                };
            };
        };
    };
    delete_movie_api_v1_library_movies__movie_id__delete: {
        parameters: {
            query?: {
                delete_files?: boolean;
            };
            header?: never;
            path: {
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_movie_api_v1_library_movies__movie_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    series_detail_api_v1_library_series__series_id__detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    series_episodes_api_v1_library_series__series_id__episodes_get: {
        parameters: {
            query?: {
                season?: number | null;
            };
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    season_monitor_api_v1_library_series__series_id__seasons__season__monitor_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
                season: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    season_search_api_v1_library_series__series_id__seasons__season__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    episodes_monitor_api_v1_library_episodes_monitor_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpisodeMonitorIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    episodes_search_api_v1_library_episodes_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpisodeIdsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_series_api_v1_library_series__series_id__delete: {
        parameters: {
            query?: {
                delete_files?: boolean;
            };
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_series_api_v1_library_series__series_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_search_api_v1_library__app___item_id__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quality_profiles_api_v1_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    services_api_v1_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceInfoOut"][];
                };
            };
        };
    };
    all_settings_api_v1_settings_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["ServiceSettingsOut"];
                    };
                };
            };
        };
    };
    save_settings_api_v1_settings_services__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_history_api_v1_stats_history_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsSampleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_service_api_v1_settings_services__name__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
